"""add_dedicated_proxy_fields

Revision ID: 958f75e5f351
Revises:
Create Date: 2025-07-07 09:06:52.805290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958f75e5f351'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy_devices', sa.Column('dedicated_port', sa.Integer(), nullable=True))
    op.add_column('proxy_devices', sa.Column('proxy_username', sa.String(length=255), nullable=True))
    op.add_column('proxy_devices', sa.Column('proxy_password', sa.String(length=255), nullable=True))
    op.add_column('proxy_devices', sa.Column('proxy_enabled', sa.Boolean(), nullable=True))
    # op.create_unique_constraint(None, 'proxy_devices', ['dedicated_port'])

    # Создание уникального индекса для dedicated_port
    op.create_index('ix_proxy_devices_dedicated_port', 'proxy_devices', ['dedicated_port'], unique=True)

    # Создание индексов для быстрого поиска
    op.create_index('ix_proxy_devices_proxy_enabled', 'proxy_devices', ['proxy_enabled'])
    op.create_index('ix_proxy_devices_proxy_username', 'proxy_devices', ['proxy_username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'proxy_devices', type_='unique')

    # Удаление индексов
    op.drop_index('ix_proxy_devices_proxy_username', table_name='proxy_devices')
    op.drop_index('ix_proxy_devices_proxy_enabled', table_name='proxy_devices')
    op.drop_index('ix_proxy_devices_dedicated_port', table_name='proxy_devices')

    op.drop_column('proxy_devices', 'proxy_enabled')
    op.drop_column('proxy_devices', 'proxy_password')
    op.drop_column('proxy_devices', 'proxy_username')
    op.drop_column('proxy_devices', 'dedicated_port')
    # ### end Alembic commands ###
